name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
    - name: 拉取项目
      uses: actions/checkout@main
    - name: SSH连接到操作
      uses: itwuge/Actions@master
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - name: 开始编译固件
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s 
    - name: 上传固件
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin

