name: Build text

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH 连接Actions'
        required: true 
        default: 'true'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
    - name: 拉取项目
      uses: actions/checkout@main
    - name: SSH连接到操作
      uses: itwuge/Actions@master
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
