name: Build OpenWrtX86

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
    - name: 拉取项目
      uses: actions/checkout@main

    - name: 初始化项目
      run: |
        export FORCE_UNSAFE_CONFIGURE=1
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
    - name: 克隆源代码
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout openwrt-23.05
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: SSH连接到操作
      uses: itwuge/Actions@master
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - name: 下载软件包
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: 开始编译固件
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s
    - name : 上传固件
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt
        path: openwrt/bin
